### ISSUE TITLE
Margin code error

### ISSUE THREAD

**Issue by c0rd94** [KuChainNetwork/Project-Deluge#3]
**Describe The Bug**

Margin trade bug seems to have auto liquidated everybody borrowing 7 day term with 0% fees on July 1st due to the Margin trading competition code which ended on the 1st of July. As per your terms and conditions, a 7 day term shall be fulfilled as it is agreed upon per purchase (the rate per day for the term). These 7 day terms should not have been auto liquidated simply because the Margin trading competition ended. 

![Screenshot_20200701-065038](https://user-images.githubusercontent.com/67698058/86256905-b6beac00-bb6d-11ea-939f-7383246b74ff.jpg)

Cordowns@gmail.com

**Comment by Pisces-Anjou** [comment]
Hi,



Thanks for your submission.

Note that Bug Bounty Program is related to KuChain, which has nothing to do with KuCoin. The issue you mentioned is out of scope. We will forward it to KuCoin security department. They will contact you if your issue is really severe for KuCoin. 

Thanks for your attention! Please keep trying and help us improve our chain.



Regards

KuChain Team
