### ISSUE TITLE
Error coding margin

### ISSUE THREAD

**Issue by mahmoud422** [KuChainNetwork/Project-Deluge#4]
Margin trade bug seems to have auto liquidated everybody borrowing 7 day term with 0% fees on July 1st due to the Margin trading competition code which ended on the 1st of July
Xsatan80@gmail.com

**Comment by Pisces-Anjou** [comment]
Hi,



Thanks for your submission.

Note that Bug Bounty Program is related to KuChain, which has nothing to do with KuCoin. The issue you mentioned is out of scope. We will forward it to KuCoin security department. They will contact you if your issue is really severe for KuCoin. 

Thanks for your attention! Please keep trying and help us improve our chain.



Regards

KuChain Team

**Comment by qhxin2** [comment]
@mahmoud422 Please contact Margin Support on KuCoin website.

![image](https://user-images.githubusercontent.com/62420158/86325466-aa704700-bc72-11ea-8a54-c153867b4b2f.png)
